# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  view:
    formats: { json: true, xml: false, rss: false }
    view_response_listener: true
  serializer:
    serialize_null: true
  body_converter:
    enabled: true
    validate: true
    validation_errors_argument: violations
  format_listener:
    rules:
      - { path: '^/', priorities: [ 'json' ], fallback_format: 'json' }
  versioning:
    enabled: true
    default_version: 1.0
    resolvers:
      custom_header:
        enabled: true
        header_name: X-Accept-Version