nelmio_api_doc:
    documentation:
        info:
            title: BileMo
            description: BileMo is an API that allows to get mobile phones list/detail for authenticated clients, and client's associated users in JSON format
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
