nelmio_api_doc:
    documentation:
        info:
            title: BileMo
            description: BileMo is an API that allows to get mobile phones list/detail for authenticated clients, and client's associated users in JSON format.<br>View code on <a href="https://github.com/Xwyk/bilemo">GitHub</a>
            version: 1.0.0
        components:
            securitySchemes:
                bearerAuth: # arbitrary name for the security scheme
                    type: http
                    scheme: bearer
                    bearerFormat: JWT    # optional, arbitrary value for documentation purposes
        security:
            - bearerAuth: [ ]
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
    models:
        names:
            - { alias: User_Create,        type: App\Entity\User, groups: [create] }
            - { alias: User,  type: App\Entity\User, groups: [ user_show_detail,Default ] }
            - { alias: User_List, type: App\Entity\User, groups: [ users_show_client_list,Default ] }
            - { alias: Address_Create, type: App\Entity\Address, groups: [ create ] }
#            - { alias: Address_Show, type: App\Entity\Address, groups: [ user_show_detail ] }
            - { alias: Product, type: App\Entity\Product, groups: [ product_show_detail,Default ] }
            - { alias: Product_List, type: App\Entity\Product, groups: [ products_show_list,Default ] }