security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        database_users:
            entity:
                class: App\Entity\Client
                property: apiToken
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: false
#            logout: ~
#            provider: database_users
#            stateless: true
#            guard:
#                authenticators:
#                    - App\Security\APIAuthenticator
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
         - { path: ^/, roles: ROLE_ADMIN }
