@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Authenticated admin" as admin
actor System                as system
actor Database              as db

admin  -> system  : send HTTP DEL /clients/{id}
system -> db      : get Client object from {id}
system <-- db     : return data

alt Client exists
  system -> db      : delete Client object
  system <-- db     : return status code
  admin  <-- system : return 200 status code
else Client doesn't exists
  admin  <-- system : return 404 status code
end

@enduml