@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Authenticated user" as user
actor System                as system
actor Database              as db

user  -> system  : send HTTP GET /products
system -> db      : request for products list
system <-- db     : return data
user  <-- system : return products list in JSON

@enduml