@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Authenticated client" as client
actor System                as system
actor Database              as db

client  -> system  : send HTTP GET /api/products
system -> db      : request for products list
system <-- db     : return data
client  <-- system : return products list in JSON

@enduml