@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Authenticated client" as client
actor System                as system
actor Database              as db

client  -> system  : send HTTP GET /api/prodcuts/{id}
system -> db      : request for Product object from {id}
system <-- db     : return data

alt Product exists
      client  <-- system : return product's details in JSON
else Product doesn't exists
  client  <-- system : return 404 status code
end

@enduml