@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Authenticated admin" as admin
actor System                as system
actor Database              as db

admin  -> system  : send HTTP POST /products with JSON object
system -> system  : create Product object from JSON object
system -> db      : Persist Product object
system <-- db     : return data
admin  <-- system : return 201 status code

@enduml