@startuml
left to right direction
Client    <<operator>> as client


rectangle "Products Management" {
  (List products) as listProducts
  (Get product details) as getDetails
  (authentication) as auth
}

client --> listProducts
client --> getDetails

listProducts ..> auth : <<include>>
getDetails ..> auth : <<include>>

@enduml
