@startuml

left to right direction

Client    <<operator>> as user
Admin    <<operator>> as admin

rectangle "Users Management" {
  (Add user) as addUser
  (Delete user) as delUser
  (List users) as listUsers
  (Show user details) as showUser
  (authentication) as auth
}

admin --> addUser
admin --> delUser
user --> showUser
user --> listUsers

addUser ..> auth : <<include>>
delUser ..> auth : <<include>>
showUser ..> auth : <<include>>
listUsers ..> auth : <<include>>

admin -|> user

@enduml
