@startuml

left to right direction

Client    <<operator>> as client

rectangle "Users Management" {
  (Add user) as addUser
  (Delete user) as delUser
  (List users) as listUsers
  (Show user details) as showUser
  (authentication) as auth
}

client --> showUser
client --> listUsers
client --> addUser
client --> delUser

showUser ..> auth : <<include>>
listUsers ..> auth : <<include>>
addUser ..> auth : <<include>>
delUser ..> auth : <<include>>

@enduml
