@startuml

left to right direction


Client    <<operator>> as client

rectangle "Authentication" {
  (Authenticate with Token) as auth
  (Get JWT Token) as getToken
}

client --> auth
client --> getToken

@enduml
