@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Authenticated admin" as admin
actor System                as system
actor Database              as db

admin  -> system  : send HTTP GET /clients/{id}/users
system -> db      : request for users list
system <-- db     : return data
admin  <-- system : return clients list in JSON

@enduml