@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Authenticated client" as client
actor System                as system
actor Database              as db

client  -> system  : send HTTP DELETE /api/users/{id}
system  -> db  : request for user
system  <-- db  : return response
alt User exists
  system  -> system  : Check if User belong to Client
  alt User belong to Client
    system -> db      : delete User object
    system <-- db     : return status code
    client  <-- system : return 200 status code
  else User doesn't exists
    client  <-- system : return 403 status code
  end
else User doesn't exists
  client  <-- system : return 404 status code
end


@enduml