@startuml
'https://plantuml.com/component-diagram

package "Application" {
  [Products Management]
  [Users Management]
  [Authentication]
}

[Products Management] ..> [Authentication] : extends
[Users Management] ..> [Authentication] : extends

@enduml