@startuml

left to right direction

Admin    <<operator>> as admin

rectangle "Clients Management" {
  (List clients) as listClient
  (Add client) as addClient
  (Delete client) as delClient
  (authentication) as auth
}

admin --> listClient
admin --> addClient
admin --> delClient

listClient ..> auth : <<include>>
addClient ..> auth : <<include>>
delClient ..> auth : <<include>>

@enduml
